name: Build and Zip Template

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Pack the template
      run: dotnet pack --configuration Release --output ./output

    - name: Create ZIP artifact
      run: |
        zip -r ./output/template.zip ./output/*

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v3
      with:
        name: template-zip
        path: ./output/template.zip
