name: Build, Pack and Release Template

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Pack the template
      run: dotnet pack --configuration Release --output ./output

    - name: Create ZIP artifact
      run: |
        zip -r ./output/template.zip ./output/*

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: template-zip
        path: ./output/template.zip

    - name: Get version from project
      id: get_version
      run: echo "VERSION=$(cat ConsoleExtended.csproj | grep -oP '(?<=<Version>).*?(?=</Version>)')" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.VERSION }}
        release_name: "Release v${{ env.VERSION }}"
        draft: false
        prerelease: false
        files: |
          ./output/ConsoleExtended.${{ env.VERSION }}.nupkg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
